package com.harmeetsingh13.entities;

// Generated 9 Nov, 2014 1:08:18 AM by Hibernate Tools 4.3.1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OauthRefreshTokenId generated by hbm2java
 */
@Embeddable
public class OauthRefreshTokenId implements java.io.Serializable {

	private String tokenId;
	private byte[] token;
	private byte[] authentication;

	public OauthRefreshTokenId() {
	}

	public OauthRefreshTokenId(String tokenId, byte[] token,
			byte[] authentication) {
		this.tokenId = tokenId;
		this.token = token;
		this.authentication = authentication;
	}

	@Column(name = "token_id", length = 256)
	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "token")
	public byte[] getToken() {
		return this.token;
	}

	public void setToken(byte[] token) {
		this.token = token;
	}

	@Column(name = "authentication")
	public byte[] getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(byte[] authentication) {
		this.authentication = authentication;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OauthRefreshTokenId))
			return false;
		OauthRefreshTokenId castOther = (OauthRefreshTokenId) other;

		return ((this.getTokenId() == castOther.getTokenId()) || (this
				.getTokenId() != null && castOther.getTokenId() != null && this
				.getTokenId().equals(castOther.getTokenId())))
				&& ((this.getToken() == castOther.getToken()) || (this
						.getToken() != null && castOther.getToken() != null && Arrays
							.equals(this.getToken(), castOther.getToken())))
				&& ((this.getAuthentication() == castOther.getAuthentication()) || (this
						.getAuthentication() != null
						&& castOther.getAuthentication() != null && Arrays
							.equals(this.getAuthentication(),
									castOther.getAuthentication())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTokenId() == null ? 0 : this.getTokenId().hashCode());
		result = 37 * result
				+ (getToken() == null ? 0 : Arrays.hashCode(this.getToken()));
		result = 37
				* result
				+ (getAuthentication() == null ? 0 : Arrays.hashCode(this
						.getAuthentication()));
		return result;
	}

}
